name: Lab Test

on:
  push:
    branches: [ "master", "code" ]
  pull_request:
    branches: [ "master", "code" ]

jobs:

  MapReduce:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run test script
      working-directory: src/main
      run: bash test-mr.sh

  Raft2A:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test 2A
      working-directory: src/raft
      run: go test -race -run 2A

    - name: Test 2A 100 times
      working-directory: src/raft
      run: bash go-test-many.sh 100 4 2A

  Raft2B:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test 2A
      working-directory: src/raft
      run: go test -race -run 2B

    - name: Test 2A 100 times
      working-directory: src/raft
      run: bash go-test-many.sh 100 4 2B
