name: Lab Test

on:
  push:
    branches: [ "main", "code" ]
  pull_request:
    branches: [ "main", "code" ]

jobs:

  MapReduce:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run test script
      working-directory: src/main
      run: bash test-mr.sh

  Raft2A:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test 2A
      working-directory: src/raft
      run: go test -race -run 2A

  Raft2B:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test 2B
      working-directory: src/raft
      run: go test -race -run 2B
      
  Raft2C:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test 2C
      working-directory: src/raft
      run: go test -race -run 2C
  Raft2D:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test 2D
      working-directory: src/raft
      run: go test -run 2D
  Raft ALL:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test Raft ALL
      working-directory: src/raft
      run: go test
  