name: Lab Test

on:
  push:
    branches: [ "main", "code" ]
  pull_request:
    branches: [ "main", "code" ]

jobs:

  MapReduce:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run test script
      working-directory: src/main
      run: bash test-mr.sh

  Raft2A:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test 2A
      working-directory: src/raft
      run: go test -race -run 2A

    - name: Test 2A 500 times
      working-directory: src/raft
      run: bash go-test-many.sh 500 4 2A
