name: Go

on:
  push:
    branches: [ "main", "code" ]
  pull_request:
    branches: [ "main", "code" ]

jobs:

  MapReduce:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run test script
      working-directory: src/main
      run: bash test-mr.sh
